rules:
  - id: custom.js.disable-example
    pattern: "1 == 1"
    message: "Placeholder rule - ignore this"
    languages: [javascript]
    severity: INFO

ignore-paths:
  - api-node/ssl/
  - api-node/healthcheck/

# Отключение правил через Semgrep ruleset запросы
rule-exceptions:
  - id: problem-based-packs.insecure-transport.js-node.using-http-server.using-http-server
    paths:
      - api-node/healthcheck/

  - id: javascript.express.security.audit.express-check-csurf-middleware-usage.express-check-csurf-middleware-usage
    paths:
      - api-node/src/

  - id: generic.secrets.security.detected-private-key.detected-private-key
    paths:
      - api-node/ssl/

# Исключение путей
exclude:
  - api-node/ssl/
  - api-node/healthcheck/
  - "**/*.min.js"
  - node_modules 