rules:
  - id: problem-based-packs.insecure-transport.js-node.using-http-server.using-http-server
    paths:
      exclude:
        - healthcheck/
    severity: WARNING

  - id: javascript.express.security.audit.express-check-csurf-middleware-usage.express-check-csurf-middleware-usage
    paths:
      exclude:
        - src/index.js
    severity: WARNING 